# Generated by Django 5.0.7 on 2024-08-02 08:15

import django.utils.timezone
import landingpage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_id', models.PositiveIntegerField(validators=[landingpage.models.validate_max_digits])),
                ('company_address', models.CharField(max_length=100)),
                ('company_city', models.CharField(max_length=20)),
                ('company_post', models.PositiveIntegerField(validators=[landingpage.models.validate_max_digits])),
                ('company_email', models.EmailField(max_length=50)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_client_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
